job_details:
  path: train.py
  n_cpus: 4
  mem: 16G

parameters:
  algorithm: ['primaldual']
  dataset: ['imagenet']
  data_dir: ['/britten1/yairc/fastdro/data']
  log_interval: [100]
  epochs: [60]
  batch_size_eval: [5000]
  momentum: [0.9]
  lr_schedule: ['constant']
  averaging: ['constant_3.0']
  wd: [1e-3]
  seed: [1]
  batch_size: [500]
  reg: [0.0]
  product:
    config1:
      geometry: ['cvar']
      size: [0.1]
      lr: [5e-2]
      lr_dual: [3e-5]
      clip: [1.0]
    config3:
      geometry: ['chi-square']
      size: [1.0]
      lr: [2e-2]
      lr_dual: [3e-11]
      clip: [-1.0]