job_details:
  path: train.py
  n_cpus: 4
  mem: 16G

parameters:
  algorithm: ['batch']
  dataset: ['imagenet']
  data_dir: ['/data']
  epochs: [30]
  batch_size_eval: [5000]
  momentum: [0.9]
  lr_schedule: ['constant']
  averaging: ['constant_3.0']
  wd: [1e-3]
  seed: [1, 10, 100, 1000, 1337]
  product:
    config1:
      geometry: ['chi-square']
      size: [1.0]
      reg: [0.0]
      batch_size: [20]
      lr: [5e-4]
    config2:
      geometry: ['chi-square']
      size: ['inf']
      reg: [0.4]
      batch_size: [20]
      lr: [5e-4]
    config3:
      geometry: ['cvar']
      size: [0.1]
      reg: [0.0]
      batch_size: [20]
      lr: [2e-4]
    config4:
      geometry: ['chi-square']
      size: [1.0]
      reg: [0.0]
      batch_size: [50]
      lr: [1e-3]
    config5:
      geometry: ['chi-square']
      size: [1.0]
      reg: [0.0]
      batch_size: [500]
      lr: [1e-2]
    config6:
      geometry: ['chi-square']
      size: [1.0]
      reg: [0.0]
      batch_size: [5000]
      lr: [1e-1]
    config7:
      geometry: ['chi-square']
      size: [1.0]
      reg: [0.0]
      batch_size: [50000]
      lr: [0.5]
    config8:
      geometry: ['chi-square']
      size: ['inf']
      reg: [0.4]
      batch_size: [50]
      lr: [1e-3]
    config9:
      geometry: ['chi-square']
      size: ['inf']
      reg: [0.4]
      batch_size: [500]
      lr: [1e-2]
    config10:
      geometry: ['chi-square']
      size: ['inf']
      reg: [0.4]
      batch_size: [5000]
      lr: [1e-1]
    config11:
      geometry: ['chi-square']
      size: ['inf']
      reg: [0.4]
      batch_size: [50000]
      lr: [2e-1]
    config12:
      geometry: ['cvar']
      size: [0.1]
      reg: [0.0]
      batch_size: [50]
      lr: [5e-4]
    config13:
      geometry: ['cvar']
      size: [0.1]
      reg: [0.0]
      batch_size: [500]
      lr: [5e-3]
    config14:
      geometry: ['cvar']
      size: [0.1]
      reg: [0.0]
      batch_size: [5000]
      lr: [5e-2]
    config15:
      geometry: ['cvar']
      size: [0.1]
      reg: [0.0]
      batch_size: [50000]
      lr: [0.2]