job_details:
  path: train.py

parameters:
  dataset: ['mnist_typed_600']
  algorithm: ['batch']
  data_dir: ['/data']
  epochs: [300]
  lr_schedule: ['constant']
  momentum: [0.9]
  averaging: ['constant_3.0']
  batch_size: [500]
  geometry: ['chi-square']
  size: [0.0]
  reg: [0.0]
  seed: [1, 10, 100, 1000, 1337]
  product:
    config1:
      lr: [5e-2]
      wd: [1e-4]
    config2:
      lr: [2e-2]
      wd: [1e-3]